[package]
name = "eat"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
categories = ["no-std", "rust-patterns", "no-std::no-alloc"]
keywords = ["ifyer", "eat"]
repository = "https://github.com/Velocifyer/eat"
rust-version = "1.85.1"
description = "Eat variables"

[dependencies]
